const dotenv = require('dotenv');
const mongoose = require('mongoose');
const Project = require('./models/Project');

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/source-spark';

const projects = [
  {
    name: 'Visual Studio Code',
    description: 'A powerful code editor with deep extension support and active community contributions.',
    repoUrl: 'https://github.com/microsoft/vscode',
    language: ['TypeScript', 'JavaScript'],
    techStack: ['Electron', 'TypeScript', 'Node.js'],
    stars: 166000,
    forks: 29000,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['editor', 'devtools', 'extensions'],
    lastUpdated: new Date('2026-04-20'),
  },
  {
    name: 'React',
    description: 'A declarative JavaScript library for building fast, interactive user interfaces.',
    repoUrl: 'https://github.com/facebook/react',
    language: ['JavaScript'],
    techStack: ['React', 'JavaScript'],
    stars: 235000,
    forks: 48000,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['ui', 'frontend', 'library'],
    lastUpdated: new Date('2026-04-18'),
  },
  {
    name: 'Vue',
    description: 'The progressive framework for building user interfaces and single-page applications.',
    repoUrl: 'https://github.com/vuejs/core',
    language: ['TypeScript', 'JavaScript'],
    techStack: ['Vue', 'TypeScript'],
    stars: 210000,
    forks: 34000,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['frontend', 'framework', 'ui'],
    lastUpdated: new Date('2026-04-19'),
  },
  {
    name: 'Next.js',
    description: 'A React framework with routing, server rendering, and production optimizations.',
    repoUrl: 'https://github.com/vercel/next.js',
    language: ['TypeScript'],
    techStack: ['React', 'Node.js', 'TypeScript'],
    stars: 130000,
    forks: 30000,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['framework', 'web', 'react'],
    lastUpdated: new Date('2026-04-21'),
  },
  {
    name: 'Express',
    description: 'Minimal and flexible Node.js web framework for APIs and server applications.',
    repoUrl: 'https://github.com/expressjs/express',
    language: ['JavaScript'],
    techStack: ['Node.js', 'Express'],
    stars: 66000,
    forks: 21000,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['backend', 'api', 'server'],
    lastUpdated: new Date('2026-04-17'),
  },
  {
    name: 'Fastify',
    description: 'Fast and low-overhead web framework for Node.js with great developer ergonomics.',
    repoUrl: 'https://github.com/fastify/fastify',
    language: ['JavaScript'],
    techStack: ['Node.js', 'Fastify'],
    stars: 35000,
    forks: 3000,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['backend', 'performance', 'api'],
    lastUpdated: new Date('2026-04-16'),
  },
  {
    name: 'Bun',
    description: 'All-in-one JavaScript runtime, bundler, test runner, and package manager.',
    repoUrl: 'https://github.com/oven-sh/bun',
    language: ['Zig', 'JavaScript'],
    techStack: ['Runtime', 'Zig'],
    stars: 85000,
    forks: 2800,
    activityLevel: 'Highest',
    competitionLevel: 'High',
    topics: ['runtime', 'tooling', 'performance'],
    lastUpdated: new Date('2026-04-22'),
  },
  {
    name: 'Astro',
    description: 'Content-focused web framework for building faster websites with islands architecture.',
    repoUrl: 'https://github.com/withastro/astro',
    language: ['TypeScript'],
    techStack: ['Astro', 'TypeScript'],
    stars: 47000,
    forks: 2400,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['framework', 'static sites', 'islands'],
    lastUpdated: new Date('2026-04-15'),
  },
  {
    name: 'Svelte',
    description: 'A compiler that generates highly efficient code for building reactive web apps.',
    repoUrl: 'https://github.com/sveltejs/svelte',
    language: ['TypeScript'],
    techStack: ['Svelte', 'TypeScript'],
    stars: 78000,
    forks: 4200,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['frontend', 'compiler', 'ui'],
    lastUpdated: new Date('2026-04-14'),
  },
  {
    name: 'Django',
    description: 'A high-level Python web framework that encourages rapid development and clean design.',
    repoUrl: 'https://github.com/django/django',
    language: ['Python'],
    techStack: ['Python', 'Django'],
    stars: 82000,
    forks: 35000,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['backend', 'framework', 'python'],
    lastUpdated: new Date('2026-04-18'),
  },
  {
    name: 'FastAPI',
    description: 'Modern Python API framework built for speed, automatic docs, and developer productivity.',
    repoUrl: 'https://github.com/fastapi/fastapi',
    language: ['Python'],
    techStack: ['Python', 'FastAPI'],
    stars: 80000,
    forks: 10000,
    activityLevel: 'Highest',
    competitionLevel: 'High',
    topics: ['api', 'backend', 'python'],
    lastUpdated: new Date('2026-04-23'),
  },
  {
    name: 'Ruby on Rails',
    description: 'A convention-over-configuration framework for building full-stack web applications.',
    repoUrl: 'https://github.com/rails/rails',
    language: ['Ruby'],
    techStack: ['Ruby', 'Rails'],
    stars: 56000,
    forks: 22000,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['backend', 'web', 'framework'],
    lastUpdated: new Date('2026-04-12'),
  },
  {
    name: 'Rust Compiler',
    description: 'The Rust programming language compiler and standard library development ecosystem.',
    repoUrl: 'https://github.com/rust-lang/rust',
    language: ['Rust'],
    techStack: ['Rust', 'LLVM'],
    stars: 110000,
    forks: 15000,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['compiler', 'systems', 'language'],
    lastUpdated: new Date('2026-04-21'),
  },
  {
    name: 'Go',
    description: 'The Go programming language source repository with compiler, tools, and standard library.',
    repoUrl: 'https://github.com/golang/go',
    language: ['Go'],
    techStack: ['Go', 'Toolchain'],
    stars: 130000,
    forks: 19000,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['language', 'compiler', 'systems'],
    lastUpdated: new Date('2026-04-20'),
  },
  {
    name: 'Deno',
    description: 'A secure runtime for JavaScript and TypeScript with modern tooling out of the box.',
    repoUrl: 'https://github.com/denoland/deno',
    language: ['TypeScript', 'Rust'],
    techStack: ['Runtime', 'Rust'],
    stars: 98000,
    forks: 5400,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['runtime', 'tooling', 'typescript'],
    lastUpdated: new Date('2026-04-22'),
  },
  {
    name: 'Linux',
    description: 'The Linux kernel source tree powering modern servers, desktops, and embedded systems.',
    repoUrl: 'https://github.com/torvalds/linux',
    language: ['C'],
    techStack: ['Kernel', 'C'],
    stars: 190000,
    forks: 65000,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['kernel', 'systems', 'os'],
    lastUpdated: new Date('2026-04-23'),
  },
  {
    name: 'Terraform',
    description: 'Infrastructure as code tool for provisioning and managing cloud resources.',
    repoUrl: 'https://github.com/hashicorp/terraform',
    language: ['Go'],
    techStack: ['Go', 'Infrastructure'],
    stars: 42000,
    forks: 9200,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['devops', 'cloud', 'infrastructure'],
    lastUpdated: new Date('2026-04-13'),
  },
  {
    name: 'Kubernetes',
    description: 'Container orchestration system for automating deployment, scaling, and management.',
    repoUrl: 'https://github.com/kubernetes/kubernetes',
    language: ['Go'],
    techStack: ['Go', 'Containers'],
    stars: 110000,
    forks: 39000,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['cloud', 'containers', 'devops'],
    lastUpdated: new Date('2026-04-19'),
  },
  {
    name: 'Electron',
    description: 'Build cross-platform desktop applications with JavaScript, HTML, and CSS.',
    repoUrl: 'https://github.com/electron/electron',
    language: ['C++', 'JavaScript'],
    techStack: ['Electron', 'Node.js'],
    stars: 110000,
    forks: 24000,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['desktop', 'apps', 'cross-platform'],
    lastUpdated: new Date('2026-04-17'),
  },
  {
    name: 'OpenTelemetry JS',
    description: 'Observability APIs and SDKs for JavaScript applications and services.',
    repoUrl: 'https://github.com/open-telemetry/opentelemetry-js',
    language: ['TypeScript'],
    techStack: ['Node.js', 'TypeScript'],
    stars: 4800,
    forks: 1600,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['observability', 'telemetry', 'sdk'],
    lastUpdated: new Date('2026-04-11'),
  },
  {
    name: 'Redwood',
    description: 'Full-stack framework for rapidly shipping web apps with strong developer experience.',
    repoUrl: 'https://github.com/redwoodjs/redwood',
    language: ['TypeScript'],
    techStack: ['React', 'Node.js', 'GraphQL'],
    stars: 20000,
    forks: 1500,
    activityLevel: 'Moderate',
    competitionLevel: 'Moderate',
    topics: ['fullstack', 'framework', 'graphql'],
    lastUpdated: new Date('2026-04-10'),
  },
  {
    name: 'SWR',
    description: 'React hooks library for remote data fetching, caching, and revalidation.',
    repoUrl: 'https://github.com/vercel/swr',
    language: ['TypeScript'],
    techStack: ['React', 'TypeScript'],
    stars: 31000,
    forks: 1800,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['data fetching', 'react', 'hooks'],
    lastUpdated: new Date('2026-04-16'),
  },
  {
    name: 'Prisma',
    description: 'Next-generation ORM for Node.js and TypeScript with a type-safe query experience.',
    repoUrl: 'https://github.com/prisma/prisma',
    language: ['TypeScript'],
    techStack: ['Node.js', 'TypeScript', 'ORM'],
    stars: 44000,
    forks: 3600,
    activityLevel: 'Highest',
    competitionLevel: 'High',
    topics: ['database', 'orm', 'backend'],
    lastUpdated: new Date('2026-04-18'),
  },
  {
    name: 'Tailwind CSS',
    description: 'Utility-first CSS framework for rapidly building custom user interfaces.',
    repoUrl: 'https://github.com/tailwindlabs/tailwindcss',
    language: ['TypeScript'],
    techStack: ['CSS', 'PostCSS'],
    stars: 88000,
    forks: 5000,
    activityLevel: 'Highest',
    competitionLevel: 'High',
    topics: ['css', 'design system', 'frontend'],
    lastUpdated: new Date('2026-04-23'),
  },
  {
    name: 'Storybook',
    description: 'Build UI components in isolation and document design systems with rich tooling.',
    repoUrl: 'https://github.com/storybookjs/storybook',
    language: ['TypeScript'],
    techStack: ['React', 'TypeScript'],
    stars: 84000,
    forks: 9500,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['components', 'docs', 'ui'],
    lastUpdated: new Date('2026-04-14'),
  },
  {
    name: 'Vite',
    description: 'Frontend build tool with lightning-fast dev server and optimized production builds.',
    repoUrl: 'https://github.com/vitejs/vite',
    language: ['TypeScript'],
    techStack: ['Build Tool', 'TypeScript'],
    stars: 72000,
    forks: 6900,
    activityLevel: 'Highest',
    competitionLevel: 'High',
    topics: ['build tool', 'frontend', 'dev server'],
    lastUpdated: new Date('2026-04-22'),
  },
  {
    name: 'NestJS',
    description: 'Progressive Node.js framework for scalable server-side applications and APIs.',
    repoUrl: 'https://github.com/nestjs/nest',
    language: ['TypeScript'],
    techStack: ['Node.js', 'TypeScript'],
    stars: 65000,
    forks: 7400,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['backend', 'framework', 'architecture'],
    lastUpdated: new Date('2026-04-12'),
  },
  {
    name: 'Supabase',
    description: 'Open source Firebase alternative with authentication, database, and storage APIs.',
    repoUrl: 'https://github.com/supabase/supabase',
    language: ['TypeScript'],
    techStack: ['Postgres', 'TypeScript'],
    stars: 76000,
    forks: 7500,
    activityLevel: 'Highest',
    competitionLevel: 'High',
    topics: ['backend', 'database', 'auth'],
    lastUpdated: new Date('2026-04-21'),
  },
  {
    name: 'Remix',
    description: 'Web framework focused on fast, resilient, and modern user experiences.',
    repoUrl: 'https://github.com/remix-run/remix',
    language: ['TypeScript'],
    techStack: ['React', 'Node.js'],
    stars: 30000,
    forks: 2700,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['framework', 'routing', 'react'],
    lastUpdated: new Date('2026-04-09'),
  },
  {
    name: 'Redash',
    description: 'Data visualization and dashboard platform for sharing insights across teams.',
    repoUrl: 'https://github.com/getredash/redash',
    language: ['Python', 'JavaScript'],
    techStack: ['React', 'Python'],
    stars: 24000,
    forks: 4000,
    activityLevel: 'Moderate',
    competitionLevel: 'Moderate',
    topics: ['analytics', 'dashboard', 'data'],
    lastUpdated: new Date('2026-04-08'),
  },
  {
    name: 'Mattermost',
    description: 'Open source collaboration and messaging platform for secure team communication.',
    repoUrl: 'https://github.com/mattermost/mattermost',
    language: ['Go', 'TypeScript'],
    techStack: ['Go', 'React'],
    stars: 30000,
    forks: 6900,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['collaboration', 'chat', 'team'],
    lastUpdated: new Date('2026-04-15'),
  },
  {
    name: 'Ansible',
    description: 'IT automation engine for configuration management, application deployment, and orchestration.',
    repoUrl: 'https://github.com/ansible/ansible',
    language: ['Python'],
    techStack: ['Python', 'Automation'],
    stars: 62000,
    forks: 26000,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['automation', 'devops', 'infrastructure'],
    lastUpdated: new Date('2026-04-11'),
  },
  {
    name: 'PocketBase',
    description: 'Open source backend in one file with real-time subscriptions and auth built in.',
    repoUrl: 'https://github.com/pocketbase/pocketbase',
    language: ['Go'],
    techStack: ['Go', 'SQLite'],
    stars: 47000,
    forks: 2600,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['backend', 'realtime', 'auth'],
    lastUpdated: new Date('2026-04-20'),
  },
  {
    name: 'Tauri',
    description: 'Framework for building smaller, faster desktop apps with web technologies and Rust.',
    repoUrl: 'https://github.com/tauri-apps/tauri',
    language: ['Rust', 'TypeScript'],
    techStack: ['Rust', 'Frontend'],
    stars: 95000,
    forks: 2800,
    activityLevel: 'Highest',
    competitionLevel: 'High',
    topics: ['desktop', 'rust', 'apps'],
    lastUpdated: new Date('2026-04-19'),
  },
  {
    name: 'CapRover',
    description: 'Application server and web dashboard that simplifies app deployment and orchestration.',
    repoUrl: 'https://github.com/caprover/caprover',
    language: ['JavaScript'],
    techStack: ['Docker', 'Node.js'],
    stars: 18000,
    forks: 1500,
    activityLevel: 'Moderate',
    competitionLevel: 'Low',
    topics: ['deployment', 'docker', 'ops'],
    lastUpdated: new Date('2026-04-07'),
  },
  {
    name: 'OpenTofu',
    description: 'Community-driven infrastructure as code tool forked from Terraform ecosystem.',
    repoUrl: 'https://github.com/opentofu/opentofu',
    language: ['Go'],
    techStack: ['Go', 'Infrastructure'],
    stars: 26000,
    forks: 700,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['devops', 'cloud', 'iac'],
    lastUpdated: new Date('2026-04-22'),
  },
  {
    name: 'Docmost',
    description: 'Open source collaborative wiki and documentation platform for product teams.',
    repoUrl: 'https://github.com/docmost/docmost',
    language: ['TypeScript'],
    techStack: ['Next.js', 'Postgres'],
    stars: 8000,
    forks: 600,
    activityLevel: 'Moderate',
    competitionLevel: 'Low',
    topics: ['docs', 'knowledge base', 'collaboration'],
    lastUpdated: new Date('2026-04-06'),
  },
  {
    name: 'Penpot',
    description: 'Open source design and prototyping platform for collaborative product teams.',
    repoUrl: 'https://github.com/penpot/penpot',
    language: ['Clojure', 'TypeScript'],
    techStack: ['Frontend', 'Clojure'],
    stars: 30000,
    forks: 2400,
    activityLevel: 'High',
    competitionLevel: 'Moderate',
    topics: ['design', 'prototype', 'collaboration'],
    lastUpdated: new Date('2026-04-18'),
  },
  {
    name: 'Strapi',
    description: 'Headless CMS for creating APIs quickly with flexible content modeling.',
    repoUrl: 'https://github.com/strapi/strapi',
    language: ['TypeScript'],
    techStack: ['Node.js', 'TypeScript'],
    stars: 64000,
    forks: 8100,
    activityLevel: 'High',
    competitionLevel: 'High',
    topics: ['cms', 'api', 'backend'],
    lastUpdated: new Date('2026-04-17'),
  },
  {
    name: 'ClickHouse',
    description: 'Fast open source column-oriented database management system for analytics.',
    repoUrl: 'https://github.com/ClickHouse/ClickHouse',
    language: ['C++'],
    techStack: ['Database', 'C++'],
    stars: 39000,
    forks: 7300,
    activityLevel: 'Highest',
    competitionLevel: 'Very High',
    topics: ['database', 'analytics', 'performance'],
    lastUpdated: new Date('2026-04-23'),
  },
];

const run = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    await Project.deleteMany({});
    await Project.insertMany(projects);
    console.log(`Seeded ${projects.length} projects`);
    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('Seed failed', error);
    process.exit(1);
  }
};

run();
